# Generated by Django 3.1.4 on 2020-12-28 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wifiyetu', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthPayments',
        ),
        migrations.DeleteModel(
            name='AuthProfile',
        ),
        migrations.DeleteModel(
            name='LMNOnline',
        ),
        migrations.RemoveField(
            model_name='mpesacallbacks',
            name='basemodel_ptr',
        ),
        migrations.RemoveField(
            model_name='mpesacalls',
            name='basemodel_ptr',
        ),
        migrations.RemoveField(
            model_name='mpesapayment',
            name='basemodel_ptr',
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='BaseModel',
        ),
        migrations.DeleteModel(
            name='MpesaCallBacks',
        ),
        migrations.DeleteModel(
            name='MpesaCalls',
        ),
        migrations.DeleteModel(
            name='MpesaPayment',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
